FROM nginx:1.15.8-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d
RUN mkdir /var/www/laravel/public -p && touch /var/www/laravel/public/index.php

COPY ./laravel /var/www/laravel
WORKDIR /var/www/laravel
