version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    ports:
      - "80:80"
    networks:
      - laranet
  laravel:
    container_name: laravel
    build:
      context: .
      dockerfile: ./Dockerfile.laravel
    networks:
      - laranet

networks:
  laranet:
    driver: bridge
    name: laranet