FROM php:8.3-cli
RUN rm -rf /var/www/html

RUN pecl install swoole
RUN docker-php-ext-install pcntl
RUN docker-php-ext-enable swoole

COPY ./laravel /var/www/laravel
WORKDIR /var/www/laravel

RUN chown -R www-data:www-data /var/www/laravel

CMD ["php", "artisan", "octane:start", "--host=0.0.0.0", "--port=80"]
